// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  mainSidebar: [
    'home',
    {
      type: 'category',
      label: 'Streaming',
      link: {
        type: 'generated-index',
        title: 'Movies / TV',
        description:
          'Guide to using apps that can be used to stream movies / tv shows',
        keywords: ['movies', 'download'],
      },
      items: [
        {
          type: 'category',
          label: 'Kodi',
          link: {
            type: 'doc',
            id: 'streaming/kodi/index',
          },
          items: [
            'streaming/kodi/intro',
            'streaming/kodi/details',
            'streaming/kodi/setup',
          ],
        },
      ],
    },
    'credits',
  ],
};

export default sidebars;
